name: Titan News Bot 18.5

on:
  schedule:
    - cron: '*/15 * * * *' # Cada 15 minutos
  workflow_dispatch: # Botón para lanzarlo a mano

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permite guardar la memoria de noticias
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install
        run: pip install -r requirements.txt

      - name: Run Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python news_bot.py

      - name: Save Memory
        run: |
          git config --global user.name 'Titan-Bot'
          git config --global user.email 'bot@titan.com'
          git add last_news_id.txt
          git commit -m "Actualizar ID de noticia" || exit 0
          git push
